# Data Analysis

## Set up

In [1]:
import pandas as pd
import pickle
import json
import glob
import os

## Load training data

In [2]:
train_set = pd.read_pickle('../input/train_set.pkl')

In [3]:
train_set

,claim,claimant,date,label,related_articles,id
9389,While arguing over President Reagan’s 1981 tax...,Sarah Sanders,2017-10-31,1,"[34218, 55700, 18736, 39031, 34219, 34220]",10354
1861,"Recently Rick Scott ""closed 30 women’s health ...",Lois Frankel,2014-09-12,0,"[73190, 76997, 38841, 77415, 77303, 9280, 8332...",2053
11035,Says Target installed urinals in a women’s bat...,Facebook posts,2016-04-22,0,"[9619, 22197]",12160
12221,"Says ""combined doses of vaccines"" have never b...",Facebook posts,2019-04-15,0,"[57163, 31528, 40908, 31536, 68904, 44601]",13458
11354,: The AMBER Alert system has been discontinu...,,2013-10-13,0,"[103978, 121475, 121849]",12504
...,...,...,...,...,...,...
2910,Health insurance costs for Floridians are up 3...,Republican Party of Florida,2014-09-23,1,"[9581, 89571, 7836, 7945, 7949, 77360, 83491, ...",3208
6096,"A photograph captures Harriet Tubman as a ""Gun...",,2019-03-25,0,"[125108, 125968, 126005]",6701
10446,"ISIS leader Abu Bakr al Baghdadi was ""released...",Jeanine Pirro,2014-06-14,0,"[80115, 93998, 5968, 175, 91475, 8710, 89881, ...",11514
5414,"""The board of a nonprofit organization on whic...",Tennessee Republican Party,2008-02-25,1,"[96453, 71123, 61, 69968, 96477]",5966
6657,"Japan announced plans to dump 920,000 tons of ...",,2017-08-22,1,"[120293, 132262]",7328

In [4]:
test_set = pd.read_pickle('../input/test_set.pkl')

## Load article data

In [5]:
articles = []

for file in glob.glob(os.path.join('../dataset/articles', '*.txt')):
    with open(file) as f:
        body = " ".join(line for line in f)
    
    base = os.path.basename(file)
    file_name = os.path.splitext(base)[0]
    
    article = (os.path.basename(file_name), body)
    articles.append(article)

In [6]:
articles_df = pd.DataFrame(articles)
articles_df.columns = ['article_id', 'article']

In [7]:
articles_df

      article_id                                            article
0          60583  These Republicans are misleading voters about ...
1         120801  They sued for Clinton's emails. Now they want ...
2          66570  Heritage's Fun With 'Defund Obamacare' Polling...
3         123469  Size of U.S. Unauthoriized Immigrant Workforce...
4          13133  Border Crossing/Entry Data\n Hide Coverage, Av...
...          ...                                                ...
64969      93026  Florida legislators hope to fix nuclear advanc...
64970       9904  A Chart Is Worth 1,000 Words\n Todd Harrison, ...
64971      87442  Prison plan assailed as 'sneaky,' misleading\n...
64972      59427  Updated: Do Russia probe attorneys’ donations ...
64973     112967  Clinton Campaign Volunteer Out Over False Obam...

[64974 rows x 2 columns]

# Related Articles

In [8]:
train_articles = []

for index, row in train_set.iterrows():
    for article in row['related_articles']:
        train_articles.append((article, row['id'], row['label']))

In [9]:
train_articles_df = pd.DataFrame(train_articles)
train_articles_df.columns = ['article_id', 'claim_id', 'label']
train_articles_df

       article_id  claim_id  label
0           34218     10354      1
1           55700     10354      1
2           18736     10354      1
3           39031     10354      1
4           34219     10354      1
...           ...       ...    ...
62323          61      5966      1
62324       69968      5966      1
62325       96477      5966      1
62326      120293      7328      1
62327      132262      7328      1

[62328 rows x 3 columns]

In [10]:
test_articles = []

for index, row in test_set.iterrows():
    for article in row['related_articles']:
        test_articles.append((article, row['id'], row['label']))

In [11]:
test_articles_df = pd.DataFrame(test_articles)
test_articles_df.columns = ['article_id', 'claim_id', 'label']

In [12]:
len(test_articles_df)

15352

In [13]:
# Associate each article with the labels of the claims that reference it

train_article_labels = train_articles_df.groupby('article_id')['label'].apply(list).to_dict()
train_article_labels

{2: [0],
 8: [0],
 15: [2],
 18: [1, 1],
 19: [1],
 21: [1, 1],
 22: [1, 0],
 23: [1, 1],
 31: [0],
 32: [0],
 33: [0],
 34: [0],
 35: [1],
 39: [1],
 40: [1],
 41: [1],
 42: [0],
 43: [0, 0],
 57: [1],
 61: [1],
 66: [0],
 67: [0],
 70: [0],
 73: [0],
 82: [1, 2],
 84: [1],
 88: [0],
 89: [2],
 90: [0, 0, 0, 0],
 92: [0],
 93: [1],
 94: [2],
 97: [1],
 98: [0],
 100: [1, 1],
 101: [0],
 105: [1],
 111: [0],
 114: [0],
 117: [0],
 119: [1],
 120: [1],
 121: [1],
 122: [0],
 123: [1],
 125: [0],
 127: [0],
 129: [1],
 131: [0],
 132: [1],
 134: [0],
 137: [1],
 138: [1],
 142: [1],
 145: [1],
 146: [1],
 148: [1],
 149: [1],
 151: [0],
 152: [1, 0],
 153: [1],
 154: [0],
 155: [1],
 156: [1],
 157: [1],
 158: [1, 0],
 159: [1],
 160: [1],
 161: [0],
 162: [1],
 163: [0],
 164: [0],
 168: [0],
 171: [0, 0, 1],
 172: [0],
 173: [0],
 175: [0, 0],
 176: [1],
 177: [0],
 178: [1],
 179: [0],
 180: [1],
 181: [0],
 183: [1],
 184: [1],
 185: [0, 0, 0, 0],
 187: [1],
 190: [0],
 200: [0],
 201: [2],
 202: [2],
 203: [0],
 204: [1],
 205: [1],
 210: [2],
 211: [2],
 215: [0],
 216: [1],
 217: [0],
 219: [1],
 221: [1],
 223: [0, 0],
 225: [2],
 228: [1],
 230: [0],
 233: [2],
 234: [1, 1, 1],
 240: [1, 0, 0],
 242: [0],
 243: [0],
 244: [1],
 246: [1, 1],
 248: [2],
 249: [0],
 250: [1],
 254: [2],
 256: [0],
 258: [0],
 259: [0, 0, 1],
 264: [0],
 265: [1],
 266: [0],
 270: [0],
 272: [1],
 274: [0],
 275: [0],
 277: [1, 1, 1],
 279: [0],
 283: [2],
 284: [0],
 286: [1, 1],
 288: [1],
 289: [0],
 291: [0],
 292: [1],
 293: [0],
 295: [0],
 296: [1],
 299: [0],
 301: [0],
 303: [0, 0],
 306: [1],
 307: [1],
 308: [2],
 309: [1],
 310: [1],
 311: [1],
 314: [0],
 316: [0],
 317: [1],
 318: [1],
 319: [0],
 321: [1],
 322: [0, 0],
 323: [0, 0, 0, 0],
 324: [1, 0, 0, 0, 0],
 325: [1],
 328: [1],
 329: [0],
 330: [0],
 331: [0, 0],
 333: [0],
 343: [0],
 344: [1],
 345: [1],
 348: [1, 0],
 350: [1],
 351: [1],
 352: [0, 1, 0, 0],
 353: [0],
 355: [0, 0],
 356: [0, 0, 0],
 358: [0],
 361: [0],
 362: [1],
 363: [0, 0],
 365: [0],
 366: [1],
 367: [1],
 372: [0],
 373: [2, 1],
 374: [1],
 375: [0],
 376: [1, 0, 1],
 377: [0, 0, 0, 0],
 378: [0, 0, 0, 0, 0],
 382: [0, 0],
 383: [0],
 384: [2],
 388: [1],
 390: [1, 1],
 391: [2],
 392: [0, 0, 0, 0],
 393: [1],
 394: [1],
 395: [2],
 396: [1],
 398: [0],
 402: [1],
 404: [0],
 405: [1],
 407: [1],
 409: [1],
 410: [0],
 411: [1],
 412: [1],
 413: [2],
 414: [0],
 416: [1],
 419: [1],
 420: [0, 0],
 422: [0],
 424: [2],
 425: [0],
 426: [1],
 427: [0, 0],
 428: [1],
 430: [1],
 433: [1],
 435: [1],
 437: [0],
 461: [0],
 462: [1],
 464: [1],
 466: [1],
 467: [1],
 474: [1],
 483: [1],
 486: [2],
 487: [1],
 488: [0],
 489: [1],
 490: [1, 1, 2],
 494: [0],
 495: [1],
 496: [1],
 497: [2],
 499: [1, 1],
 501: [1],
 503: [1],
 505: [1],
 506: [1],
 509: [1, 1],
 510: [1],
 511: [1],
 513: [0],
 516: [0],
 518: [0, 1],
 521: [1],
 522: [1],
 530: [0],
 532: [1],
 536: [0],
 537: [0],
 538: [1, 1],
 540: [1],
 541: [1],
 542: [0],
 543: [0],
 544: [0],
 545: [1],
 546: [0],
 548: [1],
 549: [1],
 550: [0],
 551: [2, 1],
 552: [1],
 554: [0],
 555: [2],
 557: [0],
 558: [1, 1],
 559: [0],
 560: [0, 0],
 562: [1, 1],
 563: [1],
 564: [1],
 574: [2],
 577: [2],
 592: [0],
 594: [1],
 596: [1],
 599: [0],
 600: [1],
 601: [1],
 602: [0],
 604: [0],
 605: [1],
 606: [0],
 607: [1],
 608: [1],
 609: [1, 1, 1, 1, 1, 1],
 610: [1, 1, 1],
 611: [1],
 618: [0],
 619: [1],
 620: [0],
 624: [0],
 625: [1],
 626: [1],
 627: [0],
 629: [0],
 630: [0],
 631: [1],
 633: [1],
 637: [1],
 643: [1],
 644: [2],
 650: [1],
 654: [1],
 656: [1],
 660: [2],
 661: [1],
 662: [2],
 668: [1],
 673: [1],
 678: [1],
 679: [1],
 680: [1],
 681: [1],
 685: [1],
 686: [1],
 700: [1],
 701: [1],
 702: [1],
 705: [1],
 706: [1, 2],
 711: [1],
 712: [1],
 716: [0],
 717: [1],
 718: [1],
 719: [1],
 720: [1],
 722: [1],
 725: [1],
 726: [0],
 730: [2],
 734: [0],
 735: [1],
 738: [0],
 742: [1],
 744: [1],
 745: [0],
 746: [0],
 751: [2],
 753: [1],
 759: [0],
 763: [1],
 765: [1],
 766: [2],
 767: [2],
 770: [1],
 771: [1],
 773: [1],
 775: [0],
 776: [1],
 777: [0],
 778: [0],
 779: [1],
 782: [1],
 783: [1],
 786: [1],
 787: [1],
 788: [1],
 789: [0],
 791: [0],
 793: [0],
 794: [0],
 795: [0],
 798: [0, 0, 0],
 799: [0],
 800: [0],
 801: [0],
 802: [0, 0],
 806: [1],
 807: [1, 1],
 809: [1, 1],
 812: [0, 0, 0],
 815: [1],
 816: [0],
 817: [1],
 819: [1],
 820: [1],
 821: [0],
 822: [1],
 823: [1],
 827: [2],
 833: [1],
 835: [1],
 837: [1],
 839: [2],
 840: [1],
 842: [0],
 844: [1],
 845: [1],
 849: [1],
 852: [0, 0, 0],
 863: [1],
 864: [1],
 865: [0],
 866: [1],
 867: [0],
 868: [1],
 869: [1],
 870: [1],
 872: [1],
 873: [0],
 874: [1],
 882: [0],
 885: [0],
 886: [1],
 890: [1],
 896: [1],
 899: [2],
 905: [1, 1],
 906: [0],
 907: [1],
 913: [0, 1, 0],
 919: [2],
 920: [2],
 921: [1],
 941: [1],
 942: [0],
 943: [0],
 948: [1],
 949: [1],
 951: [1],
 953: [1],
 955: [0],
 956: [1],
 960: [0, 0],
 961: [0],
 962: [0],
 965: [0],
 970: [0],
 971: [1],
 973: [0],
 974: [2],
 977: [1, 1, 1],
 978: [0, 0],
 979: [1],
 980: [1],
 981: [1],
 1014: [0],
 1015: [0],
 1016: [0],
 1017: [0],
 1018: [0],
 1019: [0],
 1020: [0],
 1021: [2],
 1025: [1],
 1033: [1],
 1036: [0, 0],
 1037: [1],
 1041: [0],
 1042: [1],
 1043: [0],
 1047: [1],
 1048: [1],
 1049: [0],
 1054: [1],
 1061: [0],
 1063: [2],
 1069: [0, 1],
 1070: [0],
 1071: [0],
 1074: [1],
 1075: [0],
 1076: [1],
 1077: [1],
 1078: [1],
 1081: [1],
 1082: [1],
 1083: [0],
 1086: [1],
 1087: [1],
 1088: [1],
 1092: [0],
 1094: [2],
 1096: [1],
 1100: [1],
 1101: [2],
 1102: [1],
 1104: [1],
 1105: [2],
 1106: [2],
 1107: [2],
 1110: [1],
 1111: [1],
 1113: [1],
 1116: [0],
 1117: [0],
 1121: [1, 1],
 1125: [1],
 1126: [0],
 1127: [1],
 1130: [2],
 1131: [2],
 1140: [1, 1],
 1142: [1],
 1143: [0],
 1144: [0, 0],
 1148: [1],
 1151: [1],
 1154: [2],
 1160: [1],
 1161: [1],
 1164: [1],
 1179: [1],
 1180: [1],
 1181: [0],
 1183: [1],
 1184: [0, 0, 0, 0],
 1186: [1],
 1189: [1],
 1190: [1],
 1191: [1],
 1192: [1],
 1194: [1],
 1197: [2],
 1198: [0],
 1199: [0],
 1201: [1],
 1202: [0],
 1203: [1],
 1205: [0],
 1206: [0],
 1208: [0],
 1209: [1],
 1210: [2],
 1211: [1],
 1213: [0],
 1215: [0, 0],
 1217: [1],
 1218: [1],
 1219: [2],
 1220: [1],
 1221: [1],
 1223: [2],
 1224: [1],
 1227: [1],
 1228: [1],
 1229: [1],
 1230: [1],
 1231: [1, 1],
 1232: [0],
 1233: [1],
 1234: [0],
 1235: [2],
 1236: [0],
 1237: [1],
 1238: [1],
 1240: [0],
 1241: [1],
 1242: [1],
 1243: [1],
 1244: [0],
 1245: [2],
 1246: [0],
 1248: [0, 0, 0],
 1250: [0],
 1251: [1],
 1252: [0],
 1253: [1],
 1255: [0],
 1256: [0],
 1257: [0],
 1258: [0],
 1259: [2],
 1260: [0],
 1261: [1],
 1262: [1],
 1263: [1],
 1264: [0],
 1265: [1],
 1267: [1],
 1268: [1],
 1269: [1],
 1270: [0],
 1271: [1],
 1272: [0],
 1278: [2],
 1279: [0],
 1280: [0],
 1281: [1],
 1282: [1],
 1285: [1],
 1288: [0],
 1289: [2],
 1290: [1],
 1291: [1],
 1292: [1, 1, 0],
 1293: [1, 1],
 1294: [1],
 1295: [0],
 1297: [1],
 1298: [1],
 1299: [0],
 1300: [0, 0],
 1301: [0],
 1302: [2],
 1305: [1],
 1307: [1],
 1308: [1],
 1309: [1],
 1310: [1],
 1311: [1],
 1312: [1],
 1314: [1],
 1315: [1],
 1317: [1],
 1318: [0],
 1321: [1],
 1322: [1, 1, 1],
 1323: [0],
 1324: [1],
 1325: [1],
 1326: [1],
 1330: [2, 0],
 1334: [1],
 1336: [0],
 1337: [0],
 1338: [1],
 1339: [0, 0],
 1341: [1],
 1342: [0],
 1345: [1],
 1346: [0],
 1347: [1],
 1349: [0],
 1350: [1],
 1351: [0],
 1352: [1],
 1354: [0],
 1355: [1],
 1356: [1],
 1357: [1],
 1359: [2],
 1360: [2],
 1361: [2],
 1365: [0],
 1366: [1],
 1367: [1],
 1368: [2],
 1369: [1],
 1370: [2],
 1371: [2],
 1372: [1],
 1373: [2],
 1374: [0],
 1375: [1],
 1376: [1, 1],
 1377: [1],
 1379: [1],
 1380: [1],
 1381: [1],
 1382: [1],
 1383: [2],
 1385: [2],
 1386: [1, 1],
 1388: [1],
 1389: [1],
 1394: [1],
 1397: [1],
 1398: [1],
 1399: [0],
 1401: [1],
 1402: [1],
 1403: [0],
 1404: [1],
 1408: [1],
 1409: [1],
 1410: [1],
 1411: [0],
 1412: [1],
 1413: [2],
 1414: [2],
 1416: [0],
 1417: [2],
 1418: [0],
 1419: [1],
 1420: [1],
 1422: [2],
 1423: [1],
 1424: [1],
 1425: [1],
 1426: [1],
 1429: [2],
 1431: [1],
 1434: [0, 0],
 1435: [1],
 1437: [1],
 1438: [1],
 1440: [2],
 1441: [0],
 1442: [2],
 1443: [2],
 1444: [2],
 1445: [1],
 1446: [1],
 1447: [1],
 1448: [0],
 1449: [2],
 1451: [2],
 1452: [1],
 1455: [1],
 1457: [1],
 1458: [0, 1],
 1459: [1],
 1460: [1],
 1462: [1],
 1463: [1],
 1464: [2],
 1465: [1],
 1466: [1],
 1468: [1],
 1469: [1],
 1470: [1],
 1476: [1],
 1477: [1],
 1478: [1],
 1480: [0, 1],
 1483: [1],
 1484: [1, 1],
 1485: [1],
 1486: [0],
 1487: [1],
 1488: [2, 1],
 1489: [1],
 1490: [0],
 1491: [0],
 1493: [2],
 1495: [1],
 1496: [2],
 1497: [0],
 1498: [1, 1],
 1499: [1],
 1500: [1],
 1502: [2],
 1504: [1],
 1506: [0],
 1507: [1],
 1509: [0],
 1510: [0],
 1513: [1],
 1514: [2],
 1516: [0],
 1518: [0],
 1520: [0],
 1521: [0, 0],
 1522: [1],
 1523: [1],
 1527: [0],
 1528: [0],
 1529: [0],
 1531: [1, 0],
 1539: [0, 0, 0],
 1570: [0],
 1572: [1],
 1588: [0],
 1591: [1],
 1593: [0],
 1595: [1],
 1596: [0],
 1597: [1],
 1599: [1, 1],
 1604: [1],
 1605: [1],
 1607: [0],
 1609: [2],
 1622: [0],
 1624: [0],
 1626: [1],
 1627: [1],
 1628: [1, 1, 1],
 1629: [1],
 1630: [1],
 1635: [1],
 1638: [1],
 1640: [0],
 1641: [0],
 1642: [0],
 1643: [0],
 1644: [0],
 1645: [1],
 1646: [1],
 1647: [1],
 1648: [1],
 1649: [1],
 1650: [0],
 1654: [0],
 1656: [0],
 1657: [0],
 1662: [0],
 1663: [0],
 1664: [1],
 1676: [0],
 1678: [1],
 1681: [2],
 1682: [0],
 1685: [2],
 1686: [0],
 1688: [2],
 1689: [0],
 1691: [1],
 1695: [2],
 1696: [1],
 1698: [1],
 1699: [1],
 1707: [2],
 1717: [1],
 1719: [1],
 1721: [0],
 1723: [1],
 1724: [0],
 1725: [1],
 1726: [1],
 1727: [1, 1],
 1730: [0],
 1732: [1],
 1733: [1],
 1736: [1],
 1737: [1],
 1738: [0],
 1740: [0],
 1741: [1],
 1742: [0, 1, 0],
 1743: [0],
 1749: [0],
 1750: [2],
 1752: [0, 0],
 1753: [0],
 1754: [0],
 1755: [1],
 1767: [0],
 1768: [1],
 1778: [1],
 1780: [1, 1],
 1781: [1],
 1782: [1],
 1783: [1],
 1784: [1],
 1785: [1],
 1786: [0],
 1787: [2],
 1788: [1],
 1790: [2],
 1792: [2],
 1794: [1],
 1795: [1],
 1797: [0],
 1798: [1],
 1799: [1],
 1800: [1],
 1818: [1],
 1822: [0],
 1824: [1],
 1825: [1],
 1826: [1],
 1834: [0, 0],
 1835: [0],
 1837: [0],
 1838: [0, 0],
 1839: [1],
 1841: [0],
 1842: [1, 1],
 1843: [1],
 1848: [2],
 1850: [1],
 1851: [0],
 1852: [0, 0],
 1854: [0],
 1855: [1],
 1856: [2],
 1857: [1],
 1858: [0],
 1859: [1],
 1860: [1],
 1861: [1],
 1864: [0],
 1866: [2],
 1868: [1],
 1872: [2],
 1874: [1],
 1875: [1],
 1876: [1],
 1877: [0],
 1880: [1],
 1882: [1, 0, 0],
 1883: [1],
 1884: [1],
 1885: [2],
 1886: [1],
 1887: [1],
 1888: [1],
 1889: [1],
 1890: [0],
 1891: [1],
 1893: [1],
 1894: [1],
 1895: [1],
 1896: [1],
 1897: [1],
 1899: [0],
 1900: [1],
 1901: [1],
 1902: [2],
 1904: [0],
 1906: [0],
 1910: [2],
 1916: [0],
 1917: [0],
 1919: [1],
 1921: [2],
 1922: [2],
 1923: [1],
 1925: [0],
 1927: [1],
 1931: [0],
 1935: [0],
 1942: [0],
 1944: [0],
 1947: [0, 2],
 1949: [0],
 1950: [0, 0],
 1951: [0],
 1952: [0],
 1953: [1],
 1956: [0],
 1958: [0],
 1959: [0],
 1960: [2],
 1961: [1, 1],
 1962: [1],
 1963: [1],
 1964: [2],
 1966: [1],
 1967: [1],
 1968: [2],
 1969: [1, 1],
 1977: [0],
 1979: [1],
 1994: [1],
 1996: [0],
 1998: [1, 1],
 2003: [0],
 2005: [0, 0],
 2006: [0],
 2007: [1],
 2009: [1],
 2010: [0, 0, 0, 0],
 2013: [1, 2],
 2016: [1, 1],
 2019: [0],
 2020: [1],
 2022: [1],
 2023: [0],
 2025: [0],
 2026: [2],
 2031: [0, 2],
 2032: [0, 2],
 2033: [1],
 2034: [1],
 2035: [0],
 2036: [0],
 2037: [1],
 2039: [1],
 2041: [2],
 2042: [1],
 2043: [1],
 2047: [0],
 2048: [0],
 2050: [1],
 2051: [2],
 2053: [1],
 2054: [1],
 2055: [1],
 2056: [1],
 2057: [1],
 2064: [1],
 2065: [1],
 2066: [0],
 2067: [0],
 2068: [1],
 2069: [1],
 2070: [1],
 2071: [0],
 2072: [0],
 2073: [1],
 2074: [2],
 2075: [0],
 2076: [1],
 2079: [1],
 2082: [1],
 2084: [1],
 2085: [1],
 2086: [2],
 2087: [0],
 2088: [1],
 ...}

In [14]:
test_article_labels = test_articles_df.groupby('article_id')['label'].apply(list).to_dict()

In [15]:
# Assign the average value of the label of the claims that reference the article
train_article_single_label = {}

for article_id, label in train_article_labels.items():
    train_article_single_label[article_id] = round(sum(label) / len(label))

In [16]:
# train_article_single_label
len(train_article_single_label)

51580

In [17]:
test_article_single_label = {}

for article_id, label in test_article_labels.items():
    test_article_single_label[article_id] = round(sum(label) / len(label))

In [18]:
len(test_article_single_label)

14396

In [19]:
labelled_train_articles = articles_df.copy()
labelled_test_articles = articles_df.copy()

In [20]:
import numpy as np
# Initialize all article labels to -1
labelled_train_articles['label'] = -1
labelled_test_articles['label'] = -1

In [21]:
labelled_train_articles

      article_id                                            article  label
0          60583  These Republicans are misleading voters about ...     -1
1         120801  They sued for Clinton's emails. Now they want ...     -1
2          66570  Heritage's Fun With 'Defund Obamacare' Polling...     -1
3         123469  Size of U.S. Unauthoriized Immigrant Workforce...     -1
4          13133  Border Crossing/Entry Data\n Hide Coverage, Av...     -1
...          ...                                                ...    ...
64969      93026  Florida legislators hope to fix nuclear advanc...     -1
64970       9904  A Chart Is Worth 1,000 Words\n Todd Harrison, ...     -1
64971      87442  Prison plan assailed as 'sneaky,' misleading\n...     -1
64972      59427  Updated: Do Russia probe attorneys’ donations ...     -1
64973     112967  Clinton Campaign Volunteer Out Over False Obam...     -1

[64974 rows x 3 columns]

In [22]:
# Assign labels to articles that are cited by claims in the training data
for index, row in labelled_train_articles.iterrows():
    key = int(row['article_id'])
    if key in train_article_single_label:
       labelled_train_articles.at[index, 'label'] = train_article_single_label[key]

In [23]:
labelled_train_articles

      article_id                                            article  label
0          60583  These Republicans are misleading voters about ...      0
1         120801  They sued for Clinton's emails. Now they want ...     -1
2          66570  Heritage's Fun With 'Defund Obamacare' Polling...      1
3         123469  Size of U.S. Unauthoriized Immigrant Workforce...      1
4          13133  Border Crossing/Entry Data\n Hide Coverage, Av...      1
...          ...                                                ...    ...
64969      93026  Florida legislators hope to fix nuclear advanc...     -1
64970       9904  A Chart Is Worth 1,000 Words\n Todd Harrison, ...     -1
64971      87442  Prison plan assailed as 'sneaky,' misleading\n...      0
64972      59427  Updated: Do Russia probe attorneys’ donations ...      0
64973     112967  Clinton Campaign Volunteer Out Over False Obam...      0

[64974 rows x 3 columns]

In [24]:
# Drop any articles that were not cited by any claims
df_labelled_train_articles = labelled_train_articles[labelled_train_articles.label != -1]

In [25]:
df_labelled_train_articles

      article_id                                            article  label
0          60583  These Republicans are misleading voters about ...      0
2          66570  Heritage's Fun With 'Defund Obamacare' Polling...      1
3         123469  Size of U.S. Unauthoriized Immigrant Workforce...      1
4          13133  Border Crossing/Entry Data\n Hide Coverage, Av...      1
5          21607  Pelosi Floor Speech in Opposition to the Repub...      0
...          ...                                                ...    ...
64965      58727  Trump’s claim that Kerry and Obama said discus...      0
64968      45171  FACT CHECK: Trump's Oval Office Pitch For A Bo...      1
64971      87442  Prison plan assailed as 'sneaky,' misleading\n...      0
64972      59427  Updated: Do Russia probe attorneys’ donations ...      0
64973     112967  Clinton Campaign Volunteer Out Over False Obam...      0

[51580 rows x 3 columns]

In [26]:
# Save articles
df_labelled_train_articles.to_pickle('../input/labelled_train_articles.pkl')

In [27]:
# Assign labels to articles that are cited by claims in the test data
for index, row in labelled_test_articles.iterrows():
    key = int(row['article_id'])
    if key in test_article_single_label:
       labelled_test_articles.at[index, 'label'] = test_article_single_label[key]

In [28]:
# Drop any articles that were not cited by any claims
df_labelled_test_articles = labelled_test_articles[labelled_test_articles.label != -1]

In [29]:
# Save articles
df_labelled_test_articles.to_pickle('../input/labelled_test_articles.pkl')

In [30]:
# Prepare data set for training
X_train = df_labelled_train_articles.article
y_train = df_labelled_train_articles.label
X_test = df_labelled_test_articles.article
y_test = df_labelled_test_articles.label

In [31]:
import sklearn
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

In [32]:
sm = SMOTE()
cv = CountVectorizer()
nb = MultinomialNB()

pipeline = Pipeline([('cv', cv),('sm', sm), ('nb', nb)])

In [33]:
pipeline.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('cv',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('sm',
                 SMOTE(k_neighbors=5, kind='deprecated',
                       m_neighbors='deprecated', n_jobs=1,
                       out_step='deprecated', random_state=None, ratio=None,
                       sampling_strategy='auto', svm_estimator='deprecated')),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [34]:
y_pred = pipeline.predict(X_test)

In [35]:
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred, average='macro') * 100))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 57.49%

F1 Score: 43.41

Confusion Matrix:
 [[4615 2061  206]
 [2404 3577  229]
 [ 570  650   84]]

In [36]:
with open("../models/train_articles_nb.pkl", 'wb') as f:
    pickle.dump(pipeline, f)

In [37]:
tf = TfidfVectorizer()
svm = LinearSVC()

pipeline2 = Pipeline([('tf', tf),('sm', sm), ('nb', nb)])

In [38]:
pipeline2.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('sm',
                 SMOTE(k_neighbors=5, kind='deprecated',
                       m_neighbors='deprecated', n_jobs=1,
                       out_step='deprecated', random_state=None, ratio=None,
                       sampling_strategy='auto', svm_estimator='deprecated')),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [39]:
y_pred = pipeline2.predict(X_test)

In [40]:
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred, average='macro') * 100))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 46.58%

F1 Score: 41.82

Confusion Matrix:
 [[3165 1856 1861]
 [1188 3015 2007]
 [ 312  467  525]]

In [41]:
pipeline3 = Pipeline([('tf', tf), ('nb', nb)])

In [42]:
pipeline3.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [43]:
y_pred = pipeline3.predict(X_test)

In [44]:
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred, average='macro') * 100))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 57.51%

F1 Score: 39.21

Confusion Matrix:
 [[5438 1444    0]
 [3367 2841    2]
 [ 802  502    0]]

In [45]:
counts = train_set.label.value_counts()
print(counts)

0    5954
1    5117
2    1373
Name: label, dtype: int64

In [46]:
pipeline4 = Pipeline([('cv', cv),('sm', sm), ('svm', svm)])

In [47]:
pipeline4.fit(X_train, y_train)

/home/alice/projects/fake-news-ai/venv/lib/python3.6/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

Pipeline(memory=None,
         steps=[('cv',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)...
                       m_neighbors='deprecated', n_jobs=1,
                       out_step='deprecated', random_state=None, ratio=None,
                       sampling_strategy='auto', svm_estimator='deprecated')),
                ('svm',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
                           loss='squared_hinge', max_iter=1000,
                           multi_class='ovr', penalty='l2', random_state=None,
                           tol=0.0001, verbose=0))],
         verbose=False)

In [48]:
y_pred = pipeline4.predict(X_test)

In [49]:
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred, average='macro') * 100))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 51.27%

F1 Score: 42.12

Confusion Matrix:
 [[4008 2138  736]
 [2238 3130  842]
 [ 459  602  243]]